let state={registrations:[],pending:[],driver:null,questions:[],approvedCustom:[],settings:{}};let tab='registration',adminTab='locations';
const app=document.getElementById('app'),content=document.getElementById('content'),playerNav=document.getElementById('playerNav'),adminNav=document.getElementById('adminNav');
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`$${Number(n||0).toLocaleString()}`;
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function renderPlayer(){playerNav.classList.remove('hidden');adminNav.classList.add('hidden');document.querySelectorAll('#playerNav .tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));tab==='registration'?renderRegistration():renderLicenses()}
function renderRegistration(){const p=state.pending||[],r=state.registrations||[],a=state.approvedCustom||[],s=state.settings||{};content.innerHTML=`<section class="hero"><div><span class="eyebrow">SERVICES</span><h2>Vehicle Registration</h2><p>Register dealership vehicles and manage custom plate requests.</p></div><div class="stat"><b>${r.length}</b><small>Active Records</small></div></section><div class="grid">${p.map(v=>`<article class="card"><span class="badge">AWAITING REGISTRATION</span><h3>${esc(v.vehicle_name||v.model||'Vehicle')}</h3><p>VIN: ${esc(v.vin)}<br>Sale price: ${money(v.sale_price)}</p><div class="row"><button class="primary" onclick="payReg(${v.id})">Register · ${money(s.registrationFee)}</button></div></article>`).join('')}</div><h2 class="sectionTitle">Current Registrations</h2><div class="grid">${r.length?r.map(v=>{const pending=v.custom_status==='PENDING',purchased=v.custom_status==='PURCHASED';return `<article class="card"><span class="badge ${v.state==='REGISTERED'?'good':''}">${esc(v.state)}</span><h3>${esc(v.vehicle_name||v.model||'Vehicle')}</h3><p>Plate: <strong>${esc(v.current_plate||v.assigned_plate)}</strong><br>VIN: ${esc(v.vin)}<br>Coverage: ${esc(v.registration_expires_at||'N/A')}</p><div class="row">${pending?'<span class="badge">CUSTOM PLATE PENDING</span>':purchased?'<span class="badge good">CUSTOM PLATE PURCHASED</span>':s.customEnabled?`<button class="secondary" onclick="requestCustom(${v.id})">Request Custom Plate</button>`:''}</div></article>`}).join(''):'<div class="empty">No active DMV registrations.</div>'}</div>${a.length?`<h2 class="sectionTitle">Custom Plate Approved</h2><div class="grid">${a.map(x=>`<article class="card approval"><span class="badge good">APPROVED</span><h3>Congrats, your custom plate has been approved!</h3><p>Your requested plate <strong>${esc(x.requested_plate)}</strong> has been approved for <strong>${money(s.customPrice)}</strong>.</p><div class="row"><button class="primary" onclick="buyCustom(${x.id},'bank')">Pay with Bank</button><button class="secondary" onclick="buyCustom(${x.id},'cash')">Pay with Cash</button></div></article>`).join('')}</div>`:''}`}
function payReg(id){const account=confirm('Press OK for BANK. Press Cancel for CASH.')?'bank':'cash';post('register',{id,account})}
function requestCustom(id){const plate=prompt('Enter your custom plate request. Maximum 8 characters. Letters, numbers and hyphens only:');if(!plate)return;const value=plate.trim().toUpperCase();if(value.length<1||value.length>8||!/^[A-Z0-9-]+$/.test(value)){toast('Invalid custom plate. Maximum 8 characters.');return}post('customRequest',{id,plate:value})}
function buyCustom(id,account){post('purchaseCustom',{id,account})}
function renderLicenses(){const d=state.driver||{},ls=d.licenses||[];content.innerHTML=`<section class="hero"><div><span class="eyebrow">DRIVER RECORD</span><h2>${esc(d.name||'Driver')}</h2><p>Status: <strong>${esc(d.status||'ACTIVE')}</strong> · Points: <strong>${Number(d.points||0)}</strong></p></div></section><div class="grid">${ls.map(l=>`<article class="card"><span class="badge good">${esc(l.status)}</span><h3>${esc(l.license_type).toUpperCase()}</h3><p>License: <strong>${esc(l.license_number)}</strong><br>Expires: ${esc(l.expires_at||'N/A')}</p></article>`).join('')}</div><h2 class="sectionTitle">Written Examinations</h2><div class="grid">${['standard','cdl','taxi'].map(t=>`<article class="card"><h3>${t==='standard'?'Standard / Class C':t.toUpperCase()+' License'}</h3><p>${state.questions.filter(q=>q.license_type===t).length} questions</p><button class="primary" onclick="exam('${t}')">Start Exam</button></article>`).join('')}</div><h2 class="sectionTitle">Recent Violations</h2><div class="list">${(d.violations||[]).map(v=>`<div><b>${esc(v.violation)}</b><span>+${v.points} · ${esc(v.created_at)}</span></div>`).join('')||'<div class="empty">No recent violations.</div>'}</div>`}
function exam(type){const qs=state.questions.filter(q=>q.license_type===type);content.innerHTML=`<section class="hero"><div><span class="eyebrow">WRITTEN EXAM</span><h2>${type.toUpperCase()}</h2></div></section><form id="examForm">${qs.map((q,i)=>`<article class="card"><h3>${i+1}. ${esc(q.question)}</h3>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${q.id}" value="${j}" required> ${esc(o)}</label>`).join('')}</article>`).join('')}<button class="primary" type="submit">Submit Exam</button></form>`;document.getElementById('examForm').onsubmit=e=>{e.preventDefault();const answers={};qs.forEach(q=>{const x=document.querySelector(`input[name=q${q.id}]:checked`);if(x)answers[q.id]=Number(x.value)});post('exam',{licenseType:type,answers})}}
function renderAdmin(){playerNav.classList.add('hidden');adminNav.classList.remove('hidden');document.querySelectorAll('#adminNav .tab').forEach(x=>x.classList.toggle('active',x.dataset.adminTab===adminTab));adminTab==='locations'?renderLocations():adminTab==='requests'?renderRequests():renderSettings()}
function renderLocations(){const ls=state.admin?.locations||[];content.innerHTML=`<section class="hero"><div><span class="eyebrow">ADMINISTRATION</span><h2>DMV Locations</h2><p>Add a public DMV and position its player interaction target.</p></div><button class="primary" onclick="addLocation()">+ Add New Location</button></section><div class="grid">${ls.map(l=>`<article class="card"><h3>${esc(l.label)}</h3><p>Blip: ${Number(l.x).toFixed(2)}, ${Number(l.y).toFixed(2)}, ${Number(l.z).toFixed(2)}<br>Menu target: ${l.menu_x?`${Number(l.menu_x).toFixed(2)}, ${Number(l.menu_y).toFixed(2)}, ${Number(l.menu_z).toFixed(2)}`:'Not set'}</p><div class="row"><button class="secondary" onclick="setMenu(${l.id})">Set Menu Location</button><button class="secondary" onclick="editLocation(${l.id})">Edit</button><button class="danger" onclick="deleteLocation(${l.id})">Delete</button></div></article>`).join('')}</div>`}
function addLocation(){const label=prompt('DMV location name:','Department of Motor Vehicles');if(label)post('createLocation',{label})}
function setMenu(id){post('setMenuLocation',{id});toast('Aim at the desired interaction point. Left click sets it; right click cancels.')}
function editLocation(id){const l=(state.admin.locations||[]).find(x=>x.id===id);const label=prompt('Location name:',l?.label||'DMV');if(label)post('updateLocation',{id,label,x:l.x,y:l.y,z:l.z,menu_x:l.menu_x,menu_y:l.menu_y,menu_z:l.menu_z,active:true})}
function deleteLocation(id){if(confirm('Delete this DMV location?'))post('updateLocation',{id,delete:true})}
function renderRequests(){const rs=state.admin?.requests||[];content.innerHTML=`<section class="hero"><div><span class="eyebrow">CUSTOM PLATES</span><h2>Pending Requests</h2></div></section><div class="grid">${rs.length?rs.map(r=>`<article class="card"><span class="badge">PENDING</span><h3>${esc(r.requested_plate)}</h3><p>Citizen: ${esc(r.citizenid)}<br>Vehicle: ${esc(r.vehicle_name||'Vehicle')}<br>VIN: ${esc(r.vin)}</p><div class="row"><button class="primary" onclick="review(${r.id},true)">Approve</button><button class="danger" onclick="review(${r.id},false)">Reject</button></div></article>`).join(''):'<div class="empty">No pending custom plate requests.</div>'}</div>`}
function review(id,approve){const reason=approve?'':(prompt('Reason for rejection:','Does not meet DMV requirements')||'Rejected by DMV');post('reviewCustomPlate',{id,approve,reason})}
function renderSettings(){const s=state.admin?.settings||{};content.innerHTML=`<section class="hero"><div><span class="eyebrow">ADMIN ACCESS</span><h2>DMV Configuration</h2><p>Changes are validated and saved server-side.</p></div></section><div class="settings"><label>Vehicle Registration Price<input id="registration_fee" type="number" value="${s.registrationFee||0}"></label><label>Registration Coverage Period (days)<input id="coverage" type="number" value="${s.coverageDays||365}"></label><label>License Plate Format<input id="format" value="${esc(s.plateFormat||'OR-######')}"><small># = random character</small></label><label>Custom Plate Price<input id="customPrice" type="number" value="${s.customPrice||0}"></label><label>Custom Plate Requests<select id="customEnabled"><option value="1" ${s.customEnabled?'selected':''}>Enabled</option><option value="0" ${!s.customEnabled?'selected':''}>Disabled</option></select></label><button class="primary" onclick="saveSettings()">Save Settings</button></div>`}
function saveSettings(){[['registration_fee',Number(document.getElementById('registration_fee').value)],['registration_coverage_days',Number(document.getElementById('coverage').value)],['plate_format',document.getElementById('format').value],['custom_plate_price',Number(document.getElementById('customPrice').value)],['custom_plate_enabled',document.getElementById('customEnabled').value]].forEach(([key,value])=>post('adminSetting',{key,value}));toast('Settings saved.')}
window.addEventListener('message',e=>{const m=e.data||{};if(m.action==='open'){app.classList.remove('hidden');renderPlayer()}if(m.action==='close'){app.classList.add('hidden')}if(m.action==='dashboard'){state=m.data||state;app.classList.remove('hidden');renderPlayer()}if(m.action==='openAdmin'){app.classList.remove('hidden');renderAdmin()}if(m.action==='adminData'){state.admin=m.data||{};app.classList.remove('hidden');renderAdmin()}if(m.action==='raycastEnd'&&!m.cancelled)toast('Menu target saved.')});
document.getElementById('close').onclick=()=>post('close');document.querySelectorAll('#playerNav .tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderPlayer()});document.querySelectorAll('#adminNav .tab').forEach(b=>b.onclick=()=>{adminTab=b.dataset.adminTab;renderAdmin()});window.addEventListener('keydown',e=>{if(e.key==='Escape')post('close')});window.payReg=payReg;window.requestCustom=requestCustom;window.buyCustom=buyCustom;window.exam=exam;window.setMenu=setMenu;window.addLocation=addLocation;window.editLocation=editLocation;window.deleteLocation=deleteLocation;window.review=review;window.saveSettings=saveSettings;
