let state={registrations:[],pending:[],driver:null,questions:[],approvedCustom:[],settings:{}};let tab='registration',adminTab='locations',locationDraft=null;
const app=document.getElementById('app'),content=document.getElementById('content'),playerNav=document.getElementById('playerNav'),adminNav=document.getElementById('adminNav');
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`$${Number(n||0).toLocaleString()}`;
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function renderPlayer(){playerNav.classList.remove('hidden');adminNav.classList.add('hidden');document.querySelectorAll('#playerNav .tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));tab==='registration'?renderRegistration():renderLicenses()}
function renderRegistration(){const p=state.pending||[],r=state.registrations||[],a=state.approvedCustom||[],s=state.settings||{};content.innerHTML=`<section class="hero"><div><span class="eyebrow">SERVICES</span><h2>Vehicle Registration</h2><p>Register dealership vehicles and manage custom plate requests.</p></div><div class="stat"><b>${r.length}</b><small>Active Records</small></div></section><div class="grid">${p.map(v=>`<article class="card"><span class="badge">AWAITING REGISTRATION</span><h3>${esc(v.vehicle_name||v.model||'Vehicle')}</h3><p>VIN: ${esc(v.vin)}<br>Sale price: ${money(v.sale_price)}</p><div class="row"><button class="primary" onclick="payReg(${v.id})">Register · ${money(s.registrationFee)}</button></div></article>`).join('')}</div><h2 class="sectionTitle">Current Registrations</h2><div class="grid">${r.length?r.map(v=>{const pending=v.custom_status==='PENDING',purchased=v.custom_status==='PURCHASED',approved=v.custom_status==='APPROVED';return `<article class="card"><span class="badge ${v.state==='REGISTERED'?'good':''}">${esc(v.state)}</span><h3>${esc(v.vehicle_name||v.model||'Vehicle')}</h3><p>Plate: <strong>${esc(v.current_plate||v.assigned_plate)}</strong><br>VIN: ${esc(v.vin)}<br>Coverage: ${esc(v.registration_expires_at||'N/A')}</p><div class="row">${pending?'<span class="badge">CUSTOM PLATE PENDING</span>':approved?'<span class="badge good">CUSTOM PLATE APPROVED</span>':purchased?'<span class="badge good">CUSTOM PLATE PURCHASED</span>':s.customEnabled?`<button class="secondary" onclick="requestCustom(${v.id})">Request Custom Plate</button>`:''}</div></article>`}).join(''):'<div class="empty">No active DMV registrations.</div>'}</div>${a.length?`<h2 class="sectionTitle">Custom Plate Approved</h2><div class="grid">${a.map(x=>`<article class="card approval"><span class="badge good">APPROVED</span><h3>Congrats, your custom plate has been approved!</h3><p>Your requested plate <strong>${esc(x.requested_plate)}</strong> has been approved for <strong>${money(s.customPrice)}</strong>.</p><div class="row"><button class="primary" onclick="buyCustom(${x.id},'bank')">Pay with Bank</button><button class="secondary" onclick="buyCustom(${x.id},'cash')">Pay with Cash</button></div></article>`).join('')}</div>`:''}`}
function payReg(id){const account=confirm('Press OK for BANK. Press Cancel for CASH.')?'bank':'cash';post('register',{id,account})}
function requestCustom(id){const existing=document.getElementById('plateModal');if(existing)existing.remove();const modal=document.createElement('div');modal.id='plateModal';modal.className='modal';modal.innerHTML=`<div class="modalBox"><h2>Request Custom Plate</h2><p>Enter your requested custom plate. Maximum 8 characters.</p><input id="customPlateInput" maxlength="8" autocomplete="off" placeholder="ABC1234"><div class="row"><button class="primary" id="submitCustom">Submit Request</button><button class="secondary" id="cancelCustom">Cancel</button></div></div>`;document.body.appendChild(modal);document.getElementById('customPlateInput').focus();document.getElementById('cancelCustom').onclick=()=>modal.remove();document.getElementById('submitCustom').onclick=()=>{const value=document.getElementById('customPlateInput').value.trim().toUpperCase();if(value.length<1||value.length>8||!/^[A-Z0-9-]+$/.test(value)){toast('Invalid custom plate. Maximum 8 characters.');return}post('customRequest',{id,plate:value});modal.remove()}}
function buyCustom(id,account){post('purchaseCustom',{id,account})}
function renderLicenses(){const d=state.driver||{},ls=d.licenses||[];content.innerHTML=`<section class="hero"><div><span class="eyebrow">DRIVER RECORD</span><h2>${esc(d.name||'Driver')}</h2><p>Status: <strong>${esc(d.status||'ACTIVE')}</strong> · Points: <strong>${Number(d.points||0)}</strong></p></div></section><div class="grid">${ls.map(l=>`<article class="card"><span class="badge good">${esc(l.status)}</span><h3>${esc(l.license_type).toUpperCase()}</h3><p>License: <strong>${esc(l.license_number)}</strong><br>Expires: ${esc(l.expires_at||'N/A')}</p></article>`).join('')}</div><h2 class="sectionTitle">Written Examinations</h2><div class="grid">${['standard','cdl','taxi'].map(t=>`<article class="card"><h3>${t==='standard'?'Standard / Class C':t.toUpperCase()+' License'}</h3><p>${state.questions.filter(q=>q.license_type===t).length} questions</p><button class="primary" onclick="exam('${t}')">Start Exam</button></article>`).join('')}</div><h2 class="sectionTitle">Recent Violations</h2><div class="list">${(d.violations||[]).map(v=>`<div><b>${esc(v.violation)}</b><span>+${v.points} · ${esc(v.created_at)}</span></div>`).join('')||'<div class="empty">No recent violations.</div>'}</div>`}
function exam(type){const qs=state.questions.filter(q=>q.license_type===type);content.innerHTML=`<section class="hero"><div><span class="eyebrow">WRITTEN EXAM</span><h2>${type.toUpperCase()}</h2></div></section><form id="examForm">${qs.map((q,i)=>`<article class="card"><h3>${i+1}. ${esc(q.question)}</h3>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${q.id}" value="${j}" required> ${esc(o)}</label>`).join('')}</article>`).join('')}<button class="primary" type="submit">Submit Exam</button></form>`;document.getElementById('examForm').onsubmit=e=>{e.preventDefault();const answers={};qs.forEach(q=>{const x=document.querySelector(`input[name=q${q.id}]:checked`);if(x)answers[q.id]=Number(x.value)});post('exam',{licenseType:type,answers})}}
function renderAdmin(){playerNav.classList.add('hidden');adminNav.classList.remove('hidden');document.querySelectorAll('#adminNav .tab').forEach(x=>x.classList.toggle('active',x.dataset.adminTab===adminTab));adminTab==='locations'?renderLocations():adminTab==='requests'?renderRequests():renderSettings()}
function renderLocations(){const ls=state.admin?.locations||[];content.innerHTML=`<section class="hero"><div><span class="eyebrow">ADMINISTRATION</span><h2>DMV Locations</h2><p>Create and edit DMV locations entirely from this panel.</p></div><button class="primary" onclick="addLocation()">+ Add New Location</button></section><div class="grid">${ls.map(l=>`<article class="card"><h3>${esc(l.label)}</h3><p>Blip: ${Number(l.x).toFixed(2)}, ${Number(l.y).toFixed(2)}, ${Number(l.z).toFixed(2)}<br>Menu target: ${l.menu_x?`${Number(l.menu_x).toFixed(2)}, ${Number(l.menu_y).toFixed(2)}, ${Number(l.menu_z).toFixed(2)}`:'Not set'}</p><div class="row"><button class="secondary" onclick="setMenu(${l.id})">Set Menu Location</button><button class="secondary" onclick="editLocation(${l.id})">Edit</button><button class="danger" onclick="deleteLocation(${l.id})">Delete</button></div></article>`).join('')}</div>`}
function addLocation(){locationDraft={label:'',x:null,y:null,z:null,menu_x:null,menu_y:null,menu_z:null};renderLocationEditor(false)}
function renderLocationEditor(editing){const d=locationDraft||{};content.innerHTML=`<section class="hero"><div><span class="eyebrow">${editing?'EDIT':'ADD'} DMV LOCATION</span><h2>${editing?'Edit DMV Location':'Add New DMV Location'}</h2><p>Set the map blip and player interaction target from this page.</p></div></section><div class="settings"><label>DMV Name<input id="locName" maxlength="80" value="${esc(d.label||'')}" placeholder="Los Santos DMV"></label><label>Blip Location<small id="blipStatus">${d.x!=null?`${Number(d.x).toFixed(2)}, ${Number(d.y).toFixed(2)}, ${Number(d.z).toFixed(2)}`:'Not set'}</small><button class="secondary" onclick="setBlip()">Set Blip Location Here</button></label><label>Menu Location<small id="menuStatus">${d.menu_x!=null?`${Number(d.menu_x).toFixed(2)}, ${Number(d.menu_y).toFixed(2)}, ${Number(d.menu_z).toFixed(2)}`:'Not set'}</small>${editing?`<button class="secondary" onclick="setMenu(${d.id})">Set Menu Location With Raycast</button>`:`<button class="secondary" onclick="setNewMenu()">Set Menu Location With Raycast</button>`}</label><div class="row"><button class="primary" onclick="saveLocation(${editing?'true':'false'})">Save DMV Location</button><button class="secondary" onclick="renderLocations()">Back</button></div></div>`}
function setBlip(){post('setBlipLocation');toast('Blip location captured from your current position.')}
function setNewMenu(){post('setMenuLocation',{id:-1})}
function saveLocation(editing){const label=document.getElementById('locName').value.trim();if(!label)return toast('Enter a DMV name.');if(locationDraft.x==null)return toast('Set the DMV blip location first.');if(editing){post('updateLocation',{id:locationDraft.id,label,x:locationDraft.x,y:locationDraft.y,z:locationDraft.z,menu_x:locationDraft.menu_x,menu_y:locationDraft.menu_y,menu_z:locationDraft.menu_z,active:true});toast('DMV location saved.')}else{post('createLocation',{label,x:locationDraft.x,y:locationDraft.y,z:locationDraft.z,menu_x:locationDraft.menu_x,menu_y:locationDraft.menu_y,menu_z:locationDraft.menu_z});toast('DMV location created.');setTimeout(()=>{post('adminRefresh');renderLocations()},500)}}
function setMenu(id){if(id===-1){post('setMenuLocation',{id:-1});return}post('setMenuLocation',{id});toast('Aim at the desired interaction point. Left click sets it; right click cancels.')}
function editLocation(id){const l=(state.admin.locations||[]).find(x=>x.id===id);if(!l)return;locationDraft={id:l.id,label:l.label,x:Number(l.x),y:Number(l.y),z:Number(l.z),menu_x:l.menu_x?Number(l.menu_x):null,menu_y:l.menu_y?Number(l.menu_y):null,menu_z:l.menu_z?Number(l.menu_z):null};renderLocationEditor(true)}
function deleteLocation(id){if(confirm('Delete this DMV location?'))post('updateLocation',{id,delete:true})}
function renderRequests(){const rs=state.admin?.requests||[];content.innerHTML=`<section class="hero"><div><span class="eyebrow">CUSTOM PLATES</span><h2>Pending Requests</h2></div></section><div class="grid">${rs.length?rs.map(r=>`<article class="card"><span class="badge">PENDING</span><h3>${esc(r.requested_plate)}</h3><p>Citizen: ${esc(r.citizenid)}<br>Vehicle: ${esc(r.vehicle_name||'Vehicle')}<br>VIN: ${esc(r.vin)}</p><div class="row"><button class="primary" onclick="review(${r.id},true)">Approve</button><button class="danger" onclick="review(${r.id},false)">Reject</button></div></article>`).join(''):'<div class="empty">No pending custom plate requests.</div>'}</div>`}
function review(id,approve){const reason=approve?'':(prompt('Reason for rejection:','Does not meet DMV requirements')||'Rejected by DMV');post('reviewCustomPlate',{id,approve,reason})}
function renderSettings(){const s=state.admin?.settings||{};content.innerHTML=`<section class="hero"><div><span class="eyebrow">ADMIN ACCESS</span><h2>DMV Configuration</h2><p>Changes are validated and saved server-side.</p></div></section><div class="settings"><label>Vehicle Registration Price<input id="registration_fee" type="number" value="${s.registrationFee||0}"></label><label>Registration Coverage Period (days)<input id="coverage" type="number" value="${s.coverageDays||365}"></label><label>License Plate Format<input id="format" value="${esc(s.plateFormat||'OR-######')}"><small># = random character</small></label><label>Custom Plate Price<input id="customPrice" type="number" value="${s.customPrice||0}"></label><label>Custom Plate Requests<select id="customEnabled"><option value="1" ${s.customEnabled?'selected':''}>Enabled</option><option value="0" ${!s.customEnabled?'selected':''}>Disabled</option></select></label><button class="primary" onclick="saveSettings()">Save Settings</button></div>`}
function saveSettings(){[['registration_fee',Number(document.getElementById('registration_fee').value)],['registration_coverage_days',Number(document.getElementById('coverage').value)],['plate_format',document.getElementById('format').value],['custom_plate_price',Number(document.getElementById('customPrice').value)],['custom_plate_enabled',document.getElementById('customEnabled').value]].forEach(([key,value])=>post('adminSetting',{key,value}));toast('Settings saved.')}
window.addEventListener('message',e=>{const m=e.data||{};if(m.action==='open'){app.classList.remove('hidden');renderPlayer()}if(m.action==='close'){app.classList.add('hidden')}if(m.action==='dashboard'){state=m.data||state;app.classList.remove('hidden');renderPlayer()}if(m.action==='openAdmin'){app.classList.remove('hidden');renderAdmin()}if(m.action==='adminData'){state.admin=m.data||{};app.classList.remove('hidden');renderAdmin()}if(m.action==='blipLocation'&&locationDraft){locationDraft.x=Number(m.coords.x);locationDraft.y=Number(m.coords.y);locationDraft.z=Number(m.coords.z);const el=document.getElementById('blipStatus');if(el)el.textContent=`${locationDraft.x.toFixed(2)}, ${locationDraft.y.toFixed(2)}, ${locationDraft.z.toFixed(2)}`}if(m.action==='raycastEnd'&&!m.cancelled){if(locationDraft&&m.coords){locationDraft.menu_x=Number(m.coords.x);locationDraft.menu_y=Number(m.coords.y);locationDraft.menu_z=Number(m.coords.z);const el=document.getElementById('menuStatus');if(el)el.textContent=`${locationDraft.menu_x.toFixed(2)}, ${locationDraft.menu_y.toFixed(2)}, ${locationDraft.menu_z.toFixed(2)}`}toast('Menu target saved.')}});
document.getElementById('close').onclick=()=>post('close');document.querySelectorAll('#playerNav .tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderPlayer()});document.querySelectorAll('#adminNav .tab').forEach(b=>b.onclick=()=>{adminTab=b.dataset.adminTab;renderAdmin()});window.addEventListener('keydown',e=>{if(e.key==='Escape')post('close')});window.payReg=payReg;window.requestCustom=requestCustom;window.buyCustom=buyCustom;window.exam=exam;window.setMenu=setMenu;window.addLocation=addLocation;window.editLocation=editLocation;window.deleteLocation=deleteLocation;window.review=review;window.saveSettings=saveSettings;window.setBlip=setBlip;window.setNewMenu=setNewMenu;window.saveLocation=saveLocation;window.renderLocations=renderLocations;
