let state={registrations:[],pending:[],driver:null,questions:[]};let tab='registration';
const app=document.getElementById('app'),content=document.getElementById('content');
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;','\\':'&#39;'}[c]));
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.getElementById('toast').appendChild(el);setTimeout(()=>el.remove(),3500)}
function render(){content.innerHTML=tab==='registration'?registration():licenses()}
function registration(){const p=state.pending||[],r=state.registrations||[];return `<div class="grid"><section class="card"><h2>Current Registrations</h2>${r.length?r.map(v=>`<div class="row"><div><b>${esc(v.vehicle_name||v.make+' '+v.model)}</b><div class="muted">VIN ${esc(v.vin)}</div></div><div><span class="pill success">${esc(v.current_plate)}</span><div class="muted">${esc(v.state)}</div></div></div>`).join(''):'<div class="empty">No active DMV registrations.</div>'}</section><section class="card"><h2>Vehicles Awaiting Registration</h2>${p.length?p.map(v=>`<div class="row"><div><b>${esc(v.vehicle_name||v.make+' '+v.model)}</b><div class="muted">VIN ${esc(v.vin)} · Sale $${Number(v.sale_price||0).toLocaleString()}</div><div class="muted">Temporary plate ${esc(v.temporary_plate)}</div></div><button class="action" onclick="pay(${v.id})">Register</button></div>`).join(''):'<div class="empty">No dealership purchases are awaiting registration.</div>'}</section></div>`}
function pay(id){content.insertAdjacentHTML('beforeend',`<div class="modal" id="pay"><div class="card" style="width:360px"><h2>Pay Registration</h2><p class="muted">Registration fee: $${350 .toLocaleString()}</p><div class="payment"><button class="action" onclick="finishPay(${id},'bank')">Bank</button><button class="action" onclick="finishPay(${id},'cash')">Cash</button></div><button class="tab" onclick="document.getElementById('pay').remove()">Cancel</button></div></div>`)}
function finishPay(id,account){document.getElementById('pay')?.remove();post('register',{id,account});}
function licenses(){const d=state.driver||{};const ls=d.licenses||[];return `<div class="grid"><section class="card"><h2>Driver Record</h2><div class="row"><span>License number</span><b>${esc(ls.find(x=>x.license_type==='standard')?.license_number||'Not issued')}</b></div><div class="row"><span>Driver status</span><b class="${d.status==='ACTIVE'?'success':'danger'}">${esc(d.status||'UNKNOWN')}</b></div><div class="row"><span>Current points</span><b>${Number(d.points||0)}</b></div>${['standard','cdl','taxi'].map(t=>{const x=ls.find(l=>l.license_type===t);return `<div class="row"><span>${t==='standard'?'Standard / Class C':t.toUpperCase()+' License'}</span><span class="pill">${esc(x?.status||'NOT ISSUED')}</span></div>`}).join('')}</section><section class="card"><h2>Recent Driving Violations</h2>${(d.violations||[]).length?(d.violations||[]).map(v=>`<div class="row"><div><b>${esc(v.violation)}</b><div class="muted">${esc(v.notes)}</div></div><span class="pill">+${v.points}</span></div>`).join(''):'<div class="empty">No recent violations.</div>'}</section></div><section class="card" style="margin-top:16px"><h2>Available Written Examinations</h2><div class="grid">${['standard','cdl','taxi'].map(t=>`<div class="card"><b>${t==='standard'?'Standard / Class C':t.toUpperCase()+' License'}</b><p class="muted">${state.questions.filter(q=>q.license_type===t).length} questions</p><button class="action" onclick="exam('${t}')">Start Exam</button></div>`).join('')}</div></section>`}
function exam(type){const qs=state.questions.filter(q=>q.license_type===type);content.innerHTML=`<section class="card"><h2>${type==='standard'?'Standard / Class C':type.toUpperCase()+' License'} Examination</h2><p class="muted">Passing score: 80%. Answers are validated by the server.</p><div class="exam">${qs.map((q,i)=>`<div class="question"><h3>${i+1}. ${esc(q.question)}</h3>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${q.id}" value="${j}">${esc(o)}</label>`).join('')}</div>`).join('')}</div><button class="action" style="margin-top:16px" onclick="submitExam('${type}')">Submit Examination</button></section>`}
function submitExam(type){const answers={};state.questions.filter(q=>q.license_type===type).forEach(q=>{const x=document.querySelector(`input[name=q${q.id}]:checked`);if(x)answers[q.id]=Number(x.value)});post('exam',{licenseType:type,answers})}
function showDoc(d){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="doc"><div class="doc"><span class="eyebrow">OFFICIAL DMV DOCUMENT</span><h2>${esc(d.license_type?'Driver License':d.status==='READY_FOR_PLATE'?'Vehicle Registration':'DMV Document')}</h2>${Object.entries(d).filter(([k])=>!['image','slot'].includes(k)).map(([k,v])=>`<div class="line"><span>${esc(k.replaceAll('_',' '))}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}<button class="action" style="margin-top:18px" onclick="document.getElementById('doc').remove();post('closeDocument')">Close</button></div></div>`)}
window.pay=pay;window.finishPay=finishPay;window.exam=exam;window.submitExam=submitExam;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;render()});
document.getElementById('close').onclick=()=>post('close');
window.addEventListener('keydown',e=>{if(e.key==='Escape')post('close')});
window.addEventListener('message',e=>{const m=e.data||{};if(m.action==='open'){app.classList.remove('hidden');render()}if(m.action==='close'){app.classList.add('hidden');document.getElementById('doc')?.remove()}if(m.action==='dashboard'){state=m.data||state;render()}if(m.action==='document'){showDoc(m.data||{})}});
